version: "3"

services:
  lowkey-vault:
    container_name: spring-akv-example-lowkey-vault
    image: nagyesta/lowkey-vault:2.5.6@sha256:30425d5186f37784793eae41b2cfe6dcd0e24fdf33a23347bc1e96e562bcf7ed
    ports:
      - "10543:10543"
      - "10544:10544"
    volumes:
      - ./lowkey-vault/data/keyvault.json.hbs:/data/keyvault.json.hbs
    environment:
      LOWKEY_ARGS: "--server.port=10543 --app.token.port=10544 
        --LOWKEY_VAULT_NAMES=- --LOWKEY_IMPORT_LOCATION=/data/keyvault.json.hbs"

  mysql:
    container_name: spring-akv-example-mysql
    image: mysql:8.0.39@sha256:ccb8f749bb5e59f9f8f03bf7282c7ef27a93a1814a24f0a8a926fb4e19b7fb97
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: NOT_A_SECRET_5b8538b6-2bf1-4d38-94f0-308d4fbb757b
    ports:
      - '23306:3306'