services:
  lowkey-vault:
    container_name: spring-akv-example-lowkey-vault
    image: nagyesta/lowkey-vault:2.13.0
    ports:
      - "10543:10543"
      - "10544:10544"
    volumes:
      - ./lowkey-vault/data/keyvault.json.hbs:/data/keyvault.json.hbs
    environment:
      LOWKEY_ARGS: "--server.port=10543 --app.token.port=10544 
        --LOWKEY_VAULT_NAMES=- --LOWKEY_IMPORT_LOCATION=/data/keyvault.json.hbs"

  mysql:
    container_name: spring-akv-example-mysql
    image: mysql:9.2.0
    environment:
      MYSQL_ROOT_PASSWORD: NOT_A_SECRET_5b8538b6-2bf1-4d38-94f0-308d4fbb757b
    ports:
      - '23306:3306'